id: ICE77A45A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:23:13+00:00'
last_modified: '2022-06-10T05:33:00.306906+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13616
  title: ཁྲོ་ཕུ་ལོ་ཙཱ་བ་བྱམས་པ་དཔལ་གྱི་རང་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6776':
      image_group_id: I1KG13635
      title: Volume 1 of khro phu lotsa+tsha ba byams pa dpal gyi rang rnam/
      total_pages: 158
      order: 1
      base_file: 6776.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
